apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-game-2048
  namespace: argocd
  labels:
    app: 2048
    env: {{ .Values.env }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/starchx/eks-blueprints-workloads
    targetRevision: main
    path: apps/2048
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
