apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-riker
  namespace: argocd
  labels:
    env: dev
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: team-riker
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/starchx/eks-blueprints-workloads
    targetRevision: simple
    path: applications
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true